mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/**/*.xml
    - classpath*:/mybatis/mapper/**/*.xml

  type-aliases-package: com.ctd.**.domian.**,com.point.**.domian.**
  global-config:
    db-config:
      logic-delete-value: "'DISABLE'"
      logic-not-delete-value: "'ENABLE'"
    banner: false

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 输出日志到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl