mybatis-plus:
  mapper-locations:
    - classpath*:/mybatis/mapper/**/*.xml
    - classpath*:/mapper/**/*.xml

  type-aliases-package: com.ctd.**.domian.**,com.point.**.domian.**

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 输出日志到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl