spring:
  jpa:
    database: oracle
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false
      minimum-idle: 3
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 1000
      validation-timeout: 3000
      read-only: false
      login-timeout: 5
    driver-class-name: oracle.jdbc.driver.OracleDriver